# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: atomix
description: Atomix core controllers and data stores
kubeVersion: ">=1.17.0"
type: application
version: 2.0.0
keywords:
  - atomix
home: https://atomix.io
maintainers:
  - name: Jordan Halterman
    email: jordan.halterman@intel.com
dependencies:
  - name: atomix-controller
    version: 2.0.0
    repository: file://../controller/chart
    alias: controller
  - name: atomix-runtime-controller
    version: 1.7.0
    repository: https://charts.atomix.io
    alias: runtime-controller
  - name: atomix-sidecar-controller
    version: 2.0.0
    repository: file://../sidecar/chart
    alias: sidecar-controller
  - name: atomix-raft-controller
    version: 2.0.0
    repository: file://../stores/raft/chart
    condition: stores.raft.enabled
    alias: raft-controller
  - name: atomix-shared-memory-controller
    version: 2.0.0
    repository: file://../stores/shared-memory/chart
    condition: stores.shared-memory.enabled
    alias: shared-memory-controller
  - name: atomix-pod-memory-controller
    version: 2.0.0
    repository: file://../stores/pod-memory/chart
    condition: stores.pod-memory.enabled
    alias: pod-memory-controller
  - name: atomix-consensus-controller
    version: 1.5.1
    repository: https://charts.atomix.io
    condition: stores.consensus.enabled
    alias: consensus-controller
