# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "atomix-controller.fullname" . }}
webhooks:
  - name: injector.proxy.atomix.io
    # Match only pods that opt-in to Atomix with the proxy.atomix.io/inject label
    objectSelector:
      matchLabels:
        proxy.atomix.io/inject: "true"
    rules:
      # TODO: Support UPDATE operations for pods
      - operations: [ "CREATE" ]
        apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        resources: [ "pods" ]
        scope: Namespaced
    clientConfig:
      service:
        name: {{ template "atomix-controller.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /inject-proxy
    admissionReviewVersions: [ "v1beta1" ]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 10