# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: raft.atomix.io/v1beta2
kind: RaftCluster
metadata:
  name: raft-cluster
spec:
  replicas: 1
  volumeClaimTemplate:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: raft.atomix.io/v1beta2
kind: RaftStore
metadata:
  name: raft-store
spec:
  cluster:
    name: raft-cluster
  partitions: 30
