#!/bin/bash
# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

readonly WF_DIR=".github/workflows"

DIRS="$(find . -mindepth 2 -name '*.yml' -type f -not -path "./.git*/*")"

for file in $DIRS; do
  source=$(echo "$file" | sed 's/^.\///g')
  prefix=$(dirname "$(dirname "$(dirname "$source")")" | sed 's/\//-/g')
  find $WF_DIR -type f -name "$prefix-*.yml" -delete
done

for file in $DIRS; do
  source=$(echo "$file" | sed 's/^.\///g')
  prefix=$(dirname "$(dirname "$(dirname "$source")")" | sed 's/\//-/g')
  dest="$WF_DIR/$prefix-$(basename "$source")"
  ln -s "$source" "$dest"
  echo "$source -> $dest"
done