# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Release Controller

on:
  push:
    tags:
      - 'controller/v*'

jobs:
  publish-controller:
    name: Build and publish controller
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish Docker image
        uses: ./.github/actions/docker/publish
        with:
          component: controller
          file: build/controller/Dockerfile
          repository: atomix/controller
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  publish-controller-init:
    name: Build and publish controller-init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish Docker image
        uses: ./.github/actions/docker/publish
        with:
          component: controller
          file: build/controller-init/Dockerfile
          repository: atomix/controller-init
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  publish-helm-chart:
    name: Publish Helm chart
    runs-on: ubuntu-latest
    needs:
      - publish-controller
      - publish-controller-init
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish Helm chart
        uses: ./.github/actions/helm/publish
        with:
          component: controller
