# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Lint Go Module

inputs:
  component:
    description: "The component path"
    required: true

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Lint Go module
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: ${{ inputs.component }}
