# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

.PHONY: build
build:
	$(MAKE) -C rsm build

.PHONY: test
test:
	$(MAKE) -C rsm test

.PHONY: kind
kind:
	$(MAKE) -C rsm kind
