# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

timeEncoder: RFC3339

rootLogger:
  level: info
  outputs:
    stdout:
      sink: stdout

loggers:
  test/1:
    level: debug
  test/2:
    level: warn
    outputs:
      stdout-1:
        sink: stdout-1
        level: info
  test/2/3:
    level: info
  test/3:
    level: info
    outputs:
      stdout:
        level: info
      stdout-1:
        sink: stdout-1
        level: warn
  test/kafka:
    level: info
    outputs:
      kafka:
        sink: kafka-1

sinks:
  stdout:
    path: stdout
    encoding: console
    timeEncoder: RFC3339
  stdout-1:
    path: stdout
    encoding: json
  file:
    path: file://test.log
    encoding: json