# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test Raft Store

on:
  push:
    branches:
      - 'master'
      - 'helmit'
    paths:
      - 'stores/raft/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: controller
          file: controller/build/controller/Dockerfile
          tags: atomix/controller
          outputs: type=docker,dest=/tmp/controller.tar

      - name: Share image
        uses: actions/upload-artifact@v3
        with:
          name: controller
          path: /tmp/controller.tar

  build-controller-init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: controller
          file: controller/build/controller-init/Dockerfile
          tags: atomix/controller-init
          outputs: type=docker,dest=/tmp/controller-init.tar

      - name: Share image
        uses: actions/upload-artifact@v3
        with:
          name: controller-init
          path: /tmp/controller-init.tar

  build-raft-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: stores/raft
          file: stores/raft/build/node/Dockerfile
          tags: atomix/raft-node
          outputs: type=docker,dest=/tmp/raft-node.tar

      - name: Share image
        uses: actions/upload-artifact@v3
        with:
          name: raft-node
          path: /tmp/raft-node.tar

  build-raft-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: stores/raft
          file: stores/raft/build/controller/Dockerfile
          tags: atomix/raft-controller
          outputs: type=docker,dest=/tmp/raft-controller.tar

      - name: Share image
        uses: actions/upload-artifact@v3
        with:
          name: raft-controller
          path: /tmp/raft-controller.tar

  run-tests:
    runs-on: ubuntu-latest

    needs:
      - build-controller
      - build-controller-init
      - build-raft-node
      - build-raft-controller

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Helm
        uses: ./.github/actions/setup-helm

      - name: Setup Helmit
        uses: ./.github/actions/setup-helmit

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind

      - name: Fetch atomix/controller
        uses: actions/download-artifact@v3
        with:
          name: controller
          path: /tmp

      - name: Fetch atomix/controller-init
        uses: actions/download-artifact@v3
        with:
          name: controller-init
          path: /tmp

      - name: Fetch atomix/raft-node
        uses: actions/download-artifact@v3
        with:
          name: raft-node
          path: /tmp

      - name: Fetch atomix/raft-controller
        uses: actions/download-artifact@v3
        with:
          name: raft-controller
          path: /tmp

      - name: Load Docker images
        run: |
          kind load image-archive /tmp/controller.tar
          kind load image-archive /tmp/controller-init.tar
          kind load image-archive /tmp/raft-node.tar
          kind load image-archive /tmp/raft-controller.tar

      - name: Install core controller
        run: |
          helm install \
            atomix-controller \
            ./controller/chart \
            -n kube-system \
            --set image.pullPolicy=Never \
            --set init.image.pullPolicy=Never \
            --wait

      - name: Install Raft controller
        run: |
          helm install \
            atomix-raft-controller \
            ./stores/raft/chart \
            -n kube-system \
            --set image.pullPolicy=Never \
            --set init.image.pullPolicy=Never \
            --wait

      - name: Test Raft controller
        working-directory: stores/raft/tests
        run: |
          helmit test ./... \
            --context ${{ github.workspace }} \
            --namespace test \
            --create-namespace \
            --verbose

      - name: Record k8s status
        if: failure()
        run: |
          echo "kubectl get pods --all-namespaces"
          kubectl get pods --all-namespaces
          echo "kubectl get storageprofiles --all-namespaces"
          kubectl get storageprofiles --all-namespaces
          echo "kubectl get datastores --all-namespaces"
          kubectl get datastores --all-namespaces
          echo "kubectl get raftclusters --all-namespaces"
          kubectl get raftclusters --all-namespaces
          echo "kubectl get raftstores --all-namespaces"
          kubectl get raftstores --all-namespaces
          echo "kubectl get raftpartitions --all-namespaces"
          kubectl get raftpartitions --all-namespaces
          echo "kubectl get raftreplicas --all-namespaces"
          kubectl get raftreplicas --all-namespaces
