# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Verify Raft Store

on:
  push:
    branches:
      - 'master'
      - 'actions'
      - 'test'
    paths:
      - 'stores/raft/**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      component: stores/raft

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      component: stores/raft
      chart: chart
