# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Verify Raft Store

on:
  push:
    branches:
      - 'master'
    paths:
      - 'stores/raft/**'
  pull_request:
    paths:
      - 'stores/raft/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      component: stores/raft

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      component: stores/raft
      chart: chart
