// SPDX-FileCopyrightText: 2022-present Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta3 "github.com/atomix/atomix/stores/raft/pkg/apis/raft/v1beta3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRaftPartitions implements RaftPartitionInterface
type FakeRaftPartitions struct {
	Fake *FakeRaftV1beta3
	ns   string
}

var raftpartitionsResource = schema.GroupVersionResource{Group: "raft.atomix.io", Version: "v1beta3", Resource: "raftpartitions"}

var raftpartitionsKind = schema.GroupVersionKind{Group: "raft.atomix.io", Version: "v1beta3", Kind: "RaftPartition"}

// Get takes name of the raftPartition, and returns the corresponding raftPartition object, and an error if there is any.
func (c *FakeRaftPartitions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta3.RaftPartition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(raftpartitionsResource, c.ns, name), &v1beta3.RaftPartition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta3.RaftPartition), err
}

// List takes label and field selectors, and returns the list of RaftPartitions that match those selectors.
func (c *FakeRaftPartitions) List(ctx context.Context, opts v1.ListOptions) (result *v1beta3.RaftPartitionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(raftpartitionsResource, raftpartitionsKind, c.ns, opts), &v1beta3.RaftPartitionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta3.RaftPartitionList{ListMeta: obj.(*v1beta3.RaftPartitionList).ListMeta}
	for _, item := range obj.(*v1beta3.RaftPartitionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested raftPartitions.
func (c *FakeRaftPartitions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(raftpartitionsResource, c.ns, opts))

}

// Create takes the representation of a raftPartition and creates it.  Returns the server's representation of the raftPartition, and an error, if there is any.
func (c *FakeRaftPartitions) Create(ctx context.Context, raftPartition *v1beta3.RaftPartition, opts v1.CreateOptions) (result *v1beta3.RaftPartition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(raftpartitionsResource, c.ns, raftPartition), &v1beta3.RaftPartition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta3.RaftPartition), err
}

// Update takes the representation of a raftPartition and updates it. Returns the server's representation of the raftPartition, and an error, if there is any.
func (c *FakeRaftPartitions) Update(ctx context.Context, raftPartition *v1beta3.RaftPartition, opts v1.UpdateOptions) (result *v1beta3.RaftPartition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(raftpartitionsResource, c.ns, raftPartition), &v1beta3.RaftPartition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta3.RaftPartition), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRaftPartitions) UpdateStatus(ctx context.Context, raftPartition *v1beta3.RaftPartition, opts v1.UpdateOptions) (*v1beta3.RaftPartition, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(raftpartitionsResource, "status", c.ns, raftPartition), &v1beta3.RaftPartition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta3.RaftPartition), err
}

// Delete takes name of the raftPartition and deletes it. Returns an error if one occurs.
func (c *FakeRaftPartitions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(raftpartitionsResource, c.ns, name, opts), &v1beta3.RaftPartition{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRaftPartitions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(raftpartitionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta3.RaftPartitionList{})
	return err
}

// Patch applies the patch and returns the patched raftPartition.
func (c *FakeRaftPartitions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta3.RaftPartition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(raftpartitionsResource, c.ns, name, pt, data, subresources...), &v1beta3.RaftPartition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta3.RaftPartition), err
}
