# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test Sidecar

on:
  push:
    branches:
      - 'master'
    paths:
      - 'sidecar/**'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Go linter
        uses: ./.github/actions/go/lint
        with:
          component: sidecar

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Go tests
        uses: ./.github/actions/go/test
        with:
          component: sidecar

  build-sidecar:
    name: Build sidecar image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker image
        uses: ./.github/actions/docker/build
        with:
          component: sidecar
          file: build/sidecar/Dockerfile

  build-controller:
    name: Build controller image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker image
        uses: ./.github/actions/docker/build
        with:
          component: sidecar
          file: build/controller/Dockerfile
