# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test sidecar

on:
  push:
    branches:
      - 'master'
      - 'actions'
    paths:
      - 'cli/**'
      - 'sidecar/**'
      - 'drivers/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-sidecar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build atomix/cli
        uses: docker/build-push-action@v3
        with:
          context: cli
          file: cli/build/Dockerfile
          tags: atomix/cli
          load: true

      - name: Build atomix/sidecar
        uses: docker/build-push-action@v3
        with:
          context: sidecar
          file: sidecar/build/sidecar/Dockerfile
          tags: atomix/sidecar
          outputs: type=docker,dest=/tmp/sidecar.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sidecar
          path: /tmp/sidecar.tar

  build-sidecar-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build atomix/sidecar-controller
        uses: docker/build-push-action@v3
        with:
          context: sidecar
          file: sidecar/build/controller/Dockerfile
          tags: atomix/sidecar-controller
          outputs: type=docker,dest=/tmp/sidecar-controller.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sidecar-controller
          path: /tmp/sidecar-controller.tar

  build-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build atomix/controller
        uses: docker/build-push-action@v3
        with:
          context: controller
          file: controller/build/controller/Dockerfile
          tags: atomix/controller
          outputs: type=docker,dest=/tmp/controller.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: controller
          path: /tmp/controller.tar

  build-controller-init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build atomix/controller-init
        uses: docker/build-push-action@v3
        with:
          context: controller
          file: controller/build/controller-init/Dockerfile
          tags: atomix/controller-init
          outputs: type=docker,dest=/tmp/controller-init.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: controller-init
          path: /tmp/controller-init.tar

  run-tests:
    runs-on: ubuntu-latest

    needs:
      - build-sidecar
      - build-sidecar-controller
      - build-controller
      - build-controller-init

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Helm
        uses: ./.github/actions/setup-helm

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind

      - name: Download atomix/sidecar
        uses: actions/download-artifact@v3
        with:
          name: sidecar
          path: /tmp

      - name: Download atomix/sidecar-controller
        uses: actions/download-artifact@v3
        with:
          name: sidecar-controller
          path: /tmp

      - name: Download atomix/controller
        uses: actions/download-artifact@v3
        with:
          name: controller
          path: /tmp

      - name: Download atomix/controller-init
        uses: actions/download-artifact@v3
        with:
          name: controller-init
          path: /tmp

      - name: Load Docker images
        run: |
          docker load --input /tmp/sidecar.tar
          docker load --input /tmp/sidecar-controller.tar
          docker load --input /tmp/controller.tar
          docker load --input /tmp/controller-init.tar
          docker image ls -a
          kind load docker-image atomix/sidecar atomix/sidecar-controller atomix/controller atomix/controller-init

      - name: Install core controller
        run: helm install -n kube-system atomix-controller ./controller/chart --set image.pullPolicy=Never --set init.image.pullPolicy=Never --wait

      - name: Install sidecar controller
        run: helm install -n kube-system atomix-sidecar-controller ./sidecar/chart --set image.pullPolicy=Never --wait

      - name: Run tests
        run: helm test -n kube-system atomix-sidecar-controller
