# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test sidecar

on:
  push:
    branches:
      - 'master'
      - 'actions'
    paths:
      - 'cli/**'
      - 'sidecar/**'
      - 'drivers/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: ./.github/actions/setup-go

      - name: Setup Helm
        uses: ./.github/actions/setup-helm

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind

      - name: Make CLI
        run: make
        working-directory: cli

      - name: Build atomix/cli
        uses: docker/build-push-action@v3
        with:
          context: cli
          file: cli/build/Dockerfile
          load: true
          push: false

      - name: Make sidecar
        run: make
        working-directory: sidecar

      - name: Build atomix/sidecar
        uses: docker/build-push-action@v3
        with:
          context: .
          file: drivers/shared-memory/test/Dockerfile
          load: true
          push: false

      - name: Load atomix/sidecar
        run: kind load docker-image atomix/sidecar

      - name: Build atomix/sidecar-controller
        uses: docker/build-push-action@v3
        with:
          context: sidecar/build/controller
          load: true
          push: false

      - name: Load atomix/sidecar-controller
        run: kind load docker-image atomix/sidecar-controller

      - name: Make controller
        run: make
        working-directory: controller

      - name: Build atomix/controller
        uses: docker/build-push-action@v3
        with:
          context: controller/build/controller
          load: true
          push: false

      - name: Load atomix/controller
        run: kind load docker-image atomix/controller

      - name: Build atomix/controller-init
        uses: docker/build-push-action@v3
        with:
          context: controller/build/controller-init
          load: true
          push: false

      - name: Load atomix/controller-init
        run: kind load docker-image atomix/controller-init

      - name: Install core controller
        run: helm install -n kube-system atomix-controller ./controller/chart --wait

      - name: Install sidecar controller
        run: helm install -n kube-system atomix-sidecar-controller ./sidecar/chart --wait

      - name: Run tests
        run: helm test -n kube-system atomix-sidecar-controller
