# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test sidecar

on:
  push:
    branches:
      - 'master'
      - 'actions'
    paths:
      - 'cli/**'
      - 'sidecar/**'
      - 'drivers/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: ./.github/actions/setup-go

      - name: Setup Helm
        uses: ./.github/actions/setup-helm

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind

      - name: Build CLI
        run: make
        working-directory: cli

      - name: Build controller
        run: make kind
        working-directory: controller

      - name: Build sidecar
        run: make kind
        working-directory: sidecar

      - name: Install core controller
        run: helm install -n kube-system atomix-controller ./controller/chart --wait

      - name: Run tests
        run: ct install --charts ./sidecar/chart
