# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Setup Helm

runs:
  using: composite
  steps:
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        check-latest: true

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.3.1
