# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

.PHONY: build
build:
	go build ./v1/driver/...

.PHONY: test
test:
	go test github.com/atomix/atomix/drivers/shared-memory/v1/driver/...
