# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test pod-memory driver

on:
  push:
    branches:
      - 'master'
      - 'actions'
    paths:
      - 'controller/**'
      - 'sidecar/**'
      - 'drivers/pod-memory/**'
      - 'stores/pod-memory/**'
      - 'test/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-primitives:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: ./.github/actions/setup-go

      - name: Setup Helm
        uses: ./.github/actions/setup-helm

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind

      - name: Make CLI
        run: make
        working-directory: cli

      - name: Build atomix/cli
        uses: docker/build-push-action@v3
        with:
          context: cli
          file: cli/build/Dockerfile
          tags: atomix/cli
          load: true
          push: false

      - name: Make sidecar
        run: make
        working-directory: sidecar

      - name: Build atomix/sidecar
        uses: docker/build-push-action@v3
        with:
          context: .
          file: drivers/pod-memory/test/Dockerfile
          tags: atomix/sidecar
          load: true
          push: false

      - name: Load atomix/sidecar
        run: kind load docker-image atomix/sidecar

      - name: Build atomix/sidecar-controller
        uses: docker/build-push-action@v3
        with:
          context: sidecar/build/controller
          tags: atomix/sidecar-controller
          load: true
          push: false

      - name: Load atomix/sidecar-controller
        run: kind load docker-image atomix/sidecar-controller

      - name: Make controller
        run: make
        working-directory: controller

      - name: Build atomix/controller
        uses: docker/build-push-action@v3
        with:
          context: controller/build/controller
          tags: atomix/controller
          load: true
          push: false

      - name: Load atomix/controller
        run: kind load docker-image atomix/controller

      - name: Build atomix/controller-init
        uses: docker/build-push-action@v3
        with:
          context: controller/build/controller-init
          tags: atomix/controller-init
          load: true
          push: false

      - name: Load atomix/controller-init
        run: kind load docker-image atomix/controller-init

      - name: Make store
        run: make
        working-directory: stores/pod-memory

      - name: Build atomix/pod-memory-controller
        uses: docker/build-push-action@v3
        with:
          context: stores/pod-memory/build/controller
          tags: atomix/pod-memory-controller
          load: true
          push: false

      - name: Load atomix/pod-memory-controller
        run: kind load docker-image atomix/pod-memory-controller

      - name: Make tests
        run: make
        working-directory: test

      - name: Build atomix/test
        uses: docker/build-push-action@v3
        with:
          context: test/build
          tags: atomix/test
          load: true
          push: false

      - name: Load atomix/test
        run: kind load docker-image atomix/test

      - name: Install core controller
        run: helm install -n kube-system atomix-controller ./controller/chart --wait

      - name: Install sidecar controller
        run: helm install -n kube-system atomix-sidecar-controller ./sidecar/chart --wait

      - name: Install store controller
        run: helm install -n kube-system atomix-pod-memory-controller ./stores/pod-memory/chart --wait

      - name: Setup tests
        run: kubectl create -f drivers/pod-memory/test/setup.yaml

      - name: Install tests
        run: helm install test ./test/chart -f drivers/pod-memory/test/suite.yaml --wait

      - name: Run tests
        run: helm test test
