# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Verify pod-memory Driver

on:
  push:
    branches:
      - 'master'
    paths:
      - 'drivers/pod-memory/**'
  pull_request:
    paths:
      - 'drivers/pod-memory/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      component: drivers/pod-memory
      package: github.com/atomix/atomix/drivers/pod-memory/v1/...

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      component: drivers/pod-memory
