# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

build: deps

deps: # @HELP build the chart dependencies
	helm dep update atomix
	helm dep update atomix-bench
