# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sharedmemorystores.sharedmemory.atomix.io
spec:
  group: sharedmemory.atomix.io
  scope: Namespaced
  names:
    kind: SharedMemoryStore
    listKind: SharedMemoryStoreList
    plural: sharedmemorystores
    singular: sharedmemorystore
    shortNames:
      - sms
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1"]
      clientConfig:
        service:
          name: atomix-shared-memory-controller
          namespace: kube-system
          path: /convert-store
  versions:
    - name: v1beta1
      served: true
      storage: false
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: |-
                The specification for the store.
              type: object
              properties:
                image:
                  type: string
                imagePullPolicy:
                  type: string
                  enum:
                    - Never
                    - IfNotPresent
                    - Always
                imagePullSecrets:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                securityContext:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                config:
                  type: object
                  properties:
                    server:
                      type: object
                      properties:
                        readBufferSize:
                          type: integer
                          nullable: true
                        writeBufferSize:
                          type: integer
                          nullable: true
                        maxSendMsgSize:
                          type: string
                          nullable: true
                        maxRecvMsgSize:
                          type: string
                          nullable: true
                        numStreamWorkers:
                          type: integer
                          nullable: true
                        maxConcurrentStreams:
                          type: integer
                          nullable: true
                    logging:
                      type: object
                      properties:
                        loggers:
                          type: object
                          additionalProperties:
                            type: object
                            properties:
                              level:
                                type: string
                                nullable: true
                                enum:
                                  - debug
                                  - info
                                  - warn
                                  - error
                                  - fatal
                                  - panic
                              output:
                                type: object
                                additionalProperties:
                                  type: object
                                  properties:
                                    sink:
                                      type: string
                                    level:
                                      type: string
                                      nullable: true
                                      enum:
                                        - debug
                                        - info
                                        - warn
                                        - error
                                        - fatal
                                        - panic
                        sinks:
                          type: object
                          additionalProperties:
                            type: object
                            properties:
                              encoding:
                                type: string
                                nullable: true
                                enum:
                                  - console
                                  - json
                              stdout:
                                type: object
                                properties: {}
                              stderr:
                                type: object
                                properties: {}
                              file:
                                type: object
                                properties:
                                  path:
                                    type: string
                                required:
                                  - path
            status:
              type: object
              properties:
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
      additionalPrinterColumns:
        - name: Status
          type: string
          description: The store state
          jsonPath: .status.state
    - name: v1beta2
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: |-
                The specification for the store.
              type: object
              default: {}
              properties:
                image:
                  type: string
                imagePullPolicy:
                  type: string
                  enum:
                    - Never
                    - IfNotPresent
                    - Always
                imagePullSecrets:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                securityContext:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                logging:
                  type: object
                  default: {}
                  properties:
                    encoding:
                      type: string
                      default: console
                      enum:
                        - console
                        - json
                    rootLevel:
                      type: string
                      default: info
                      enum:
                        - debug
                        - info
                        - warn
                        - error
                        - fatal
                        - panic
                    loggers:
                      type: array
                      items:
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                          level:
                            type: string
                            nullable: true
                            enum:
                              - debug
                              - info
                              - warn
                              - error
                              - fatal
                              - panic
            status:
              type: object
              properties:
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
      additionalPrinterColumns:
        - name: Status
          type: string
          description: The store state
          jsonPath: .status.state