# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: atomix-controller
description: The core Atomix controller provides custom resources for Atomix data stores
kubeVersion: ">=1.17.0"
type: application
# The 0.0.0 version is a placeholder. The 'version' and 'appVersion' keys are
# set to the version specified by the tag when the chart is packaged for release.
version: 0.0.0
keywords:
- atomix
home: https://atomix.io
maintainers:
- name: Jordan Halterman
  email: jordan.halterman@intel.com
