# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Create a DataStore with the configuration for the store
apiVersion: atomix.io/v3beta4
kind: DataStore
metadata:
  name: custom-example-store
spec:
  # Configure the DataStore to use a custom-built driver/version
  driver:
    name: atomix.io/custom-store
    apiVersion: v1
  # Define the configuration to be passed to the driver to connect to the store
  config:
    address: custom-store:1234
---
# Create a StorageProfile to bind your application to the store
apiVersion: atomix.io/v3beta4
kind: StorageProfile
metadata:
  name: custom-example
spec:
  # Route the profile to the custom-example-store
  routes:
    - store:
        name: custom-example-store
---
# Create a Deployment annotating the pods to use the StorageProfile
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-example
  labels:
    app: custom-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-example
  template:
    metadata:
      labels:
        app: custom-example
        # Inject the sidecar into the pods
        sidecar.atomix.io/inject: "true"
        # Configure the sidecar to use the custom-example profile
        runtime.atomix.io/profile: custom-example
      annotations:
        # Configure the sidecar to use a custom-built proxy image
        sidecar.atomix.io/image: atomix/proxy:custom-store-1.0.0
    spec:
      containers:
        - name: sleep
          image: alpine:latest
          command: ["/bin/sh", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
