# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: sharedmemory.atomix.io/v1beta1
kind: SharedMemoryStore
metadata:
  name: shared-memory-example-store
---
apiVersion: atomix.io/v3beta4
kind: StorageProfile
metadata:
  name: shared-memory-example
spec:
  # Route the profile to the shared-memory-example-store
  routes:
    - store:
        name: shared-memory-example-store
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-memory-example
  labels:
    app: shared-memory-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-memory-example
  template:
    metadata:
      labels:
        app: shared-memory-example
        # Inject the sidecar into the pods
        sidecar.atomix.io/inject: "true"
        # Configure the sidecar to use the shared-memory-example profile
        runtime.atomix.io/profile: shared-memory-example
    spec:
      containers:
        - name: sleep
          image: alpine:latest
          command: ["/bin/sh", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
