# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Build Docker image

inputs:
  name:
    description: 'The name of the image to build'
    required: true

  context:
    description: 'The Docker context'
    required: false
    default: '.'

  file:
    description: 'The Dockerfile'
    required: false

  tags:
    description: 'The image tags'
    required: false

runs:
  using: composite
  steps:
    - name: Cache image
      id: cache-image
      uses: actions/cache@v3
      with:
        path: /tmp/*.tar
        key: ${{ runner.os }}-images-${{ hashFiles(format('{0}/**', inputs.context)) }}

    - name: Set up Docker Buildx
      if: steps.cache-image.outputs.cache-hit != 'true'
      uses: docker/setup-buildx-action@v2

    - name: Build image
      if: steps.cache-image.outputs.cache-hit != 'true'
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        tags: ${{ inputs.tags }}
        outputs: type=docker,dest=/tmp/${{ inputs.name }}.tar
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Share image
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: /tmp/${{ inputs.name }}.tar
