# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Verify CLI

on:
  push:
    branches:
      - 'master'
      - 'actions'
    paths:
      - 'cli/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go environment
      uses: ./.github/actions/setup-go

    - name: Run tests
      run: go test ./...
      working-directory: cli

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      component: cli
