# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: atomix-pod-memory-controller
description: The pod memory controller extends the Kubernetes API with custom resources for pod-local shared memory stores.
kubeVersion: ">=1.17.0"
type: application
# The 0.0.0 version is a placeholder. The 'version' and 'appVersion' keys are
# set to the version specified by the tag when the chart is packaged for release.
version: 0.0.0
keywords:
- atomix
- memory
home: https://atomix.io
maintainers:
- name: Jordan Halterman
  email: jordan.halterman@intel.com
