# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Release pod-memory Store

on:
  push:
    tags:
      - 'stores/pod-memory/v*'

jobs:
  parse-and-validate-version:
    runs-on: ubuntu-latest
    outputs:
      semantic-version: ${{ steps.parse-version.outputs.semantic-version }}
      prerelease-version: ${{ steps.parse-version.outputs.prerelease-version }}
      minor-version: ${{ steps.parse-version.outputs.minor-version }}
      patch-version: ${{ steps.parse-version.outputs.patch-version }}
    steps:
      - name: Parse and validate release version
        id: parse-version
        uses: ./.github/actions/parse-version
        with:
          prefix: stores/pod-memory/

  build-and-push:
    runs-on: ubuntu-latest
    needs: parse-and-validate-version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Docker
        uses: ./.github/actions/setup-docker
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push controller
        uses: docker/build-push-action@v3
        with:
          context: stores/pod-memory
          file: build/controller/Dockerfile
          tags: ${{ needs.parse-and-validate-version.outputs.prerelease-version != '' && format('atomix/pod-memory-controller:v{0}', needs.parse-and-validate-version.outputs.prerelease-version) || format('atomix/pod-memory-controller:latest,atomix/pod-memory-controller:v{0},atomix/pod-memory-controller:v{1}', needs.parse-and-validate-version.outputs.minor-version, needs.parse-and-validate-version.outputs.patch-version) }}
          push: true

      - name: Build and push node
        uses: docker/build-push-action@v3
        with:
          context: stores/pod-memory
          file: build/node/Dockerfile
          tags: ${{ needs.parse-and-validate-version.outputs.prerelease-version != '' && format('atomix/pod-memory-node:v{0}', needs.parse-and-validate-version.outputs.prerelease-version) || format('atomix/pod-memory-node:latest,atomix/pod-memory-node:v{0},atomix/pod-memory-node:v{1}', needs.parse-and-validate-version.outputs.minor-version, needs.parse-and-validate-version.outputs.patch-version) }}
          push: true

  package-and-release:
    runs-on: ubuntu-latest
    needs:
      - parse-and-validate-version
      - build-and-push
    steps:
      - name: Setup Helm
        uses: ./.github/actions/setup-helm

      - name: Update chart dependencies
        run: helm dep update stores/pod-memory/chart

      - name: Package Helm chart
        run: |
          helm package stores/pod-memory/chart \
            --version ${{ needs.parse-and-validate-version.outputs.semantic-version }} \
            --app-version "v${{ needs.parse-and-validate-version.outputs.semantic-version }}" \
            --destination .deploy

      - name: Publish Helm chart
        uses: helm/chart-releaser-action@v1.5.0
        with:
          skip_packaging: true
        env:
          CR_TOKEN: "${{ github.token }}"
          CR_PACKAGE_PATH: .deploy
          CR_SKIP_EXISTING: true
