# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Verify pod-memory Store

on:
  push:
    branches:
      - 'master'
    paths:
      - 'stores/pod-memory/**'
  pull_request:
    paths:
      - 'stores/pod-memory/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      component: stores/pod-memory

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      component: stores/pod-memory
      chart: chart
