# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Debug workflow

on:
  push:
    branches:
      - 'master'
      - 'actions'
    paths:
      - 'controller/**'
      - 'sidecar/**'
      - 'drivers/raft/**'
      - 'stores/raft/**'
      - 'test/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: ./.github/actions/setup-go

      - name: Setup Helm
        uses: ./.github/actions/setup-helm

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind

      - name: Make controller
        run: make
        working-directory: controller

      - name: Build atomix/controller
        uses: docker/build-push-action@v3
        with:
          context: controller/build/controller
          tags: atomix/controller
          load: true
          push: false

      - name: Load atomix/controller
        run: kind load docker-image atomix/controller

      - name: Build atomix/controller-init
        uses: docker/build-push-action@v3
        with:
          context: controller/build/controller-init
          tags: atomix/controller-init
          load: true
          push: false

      - name: Load atomix/controller-init
        run: kind load docker-image atomix/controller-init

      - name: Install core controller
        id: install-controller
        run: helm install -n kube-system atomix-controller ./controller/chart --set image.pullPolicy=Never --set init.image.pullPolicy=Never --wait

      - name: Fetch status
        if: failure()
        run: |
          echo "kubectl get pods -n kube-system"
          kubectl get pods -n kube-system

      - name: Fetch logs
        if: steps.install-controller.outcome == 'failure'
        run: kubectl logs -n kube-system deployment/atomix-controller
