# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test raft driver

on:
  push:
    branches:
      - 'master'
      - 'actions'
    paths:
      - 'controller/**'
      - 'sidecar/**'
      - 'drivers/raft/**'
      - 'stores/raft/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: ./.github/actions/setup-helm

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: test

      - name: Build atomix/controller
        uses: docker/build-push-action@v3
        with:
          context: controller
          file: controller/build/controller/Dockerfile
          tags: atomix/controller
          load: true
          push: false

      - name: Build atomix/controller-init
        uses: docker/build-push-action@v3
        with:
          context: controller
          file: controller/build/controller-init/Dockerfile
          tags: atomix/controller-init
          load: true
          push: false

      - name: Build atomix/sidecar
        uses: docker/build-push-action@v3
        with:
          context: .
          file: drivers/raft/test/Dockerfile
          tags: atomix/sidecar
          load: true
          push: false

      - name: Build atomix/sidecar-controller
        uses: docker/build-push-action@v3
        with:
          context: sidecar
          file: sidecar/build/controller/Dockerfile
          tags: atomix/sidecar-controller
          load: true
          push: false

      - name: Build atomix/raft-controller
        uses: docker/build-push-action@v3
        with:
          context: stores/raft
          file: stores/raft/build/controller/Dockerfile
          tags: atomix/raft-controller
          load: true
          push: false

      - name: Build atomix/raft-node
        uses: docker/build-push-action@v3
        with:
          context: stores/raft
          file: stores/raft/build/node/Dockerfile
          tags: atomix/raft-node
          load: true
          push: false

      - name: Load images
        run: kind load docker-image atomix/controller atomix/controller-init atomix/sidecar atomix/sidecar-controller atomix/raft-controller atomix/raft-node --name test

      - name: Install core controller
        run: helm install -n kube-system atomix-controller ./controller/chart --wait

      - name: Install sidecar controller
        run: helm install -n kube-system atomix-sidecar-controller ./sidecar/chart --wait

      - name: Install store controller
        run: helm install -n kube-system atomix-raft-controller ./stores/raft/chart --wait

      - name: Run tests
        run: ct install --charts ./store/raft/test
