# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test raft driver

on:
  push:
    branches:
      - 'master'
      - 'actions'
    paths:
      - 'controller/**'
      - 'sidecar/**'
      - 'drivers/raft/**'
      - 'stores/raft/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: ./.github/actions/setup-go

      - name: Setup Helm
        uses: ./.github/actions/setup-helm

      - name: Build sidecar
        run: docker build . -t atomix/sidecar -f drivers/raft/test/Dockerfile

      - name: Build controller
        run: make
        working-directory: controller

      - name: Build sidecar controller
        run: make controller
        working-directory: sidecar

      - name: Build store
        run: make
        working-directory: stores/raft

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: test

      - name: Load images
        run: kind load docker-image atomix/controller atomix/controller-init atomix/sidecar atomix/sidecar-controller atomix/raft-controller atomix/raft-node --name test

      - name: Install core controller
        run: helm install -n kube-system atomix-controller ./controller/chart --wait

      - name: Install sidecar controller
        run: helm install -n kube-system atomix-sidecar-controller ./sidecar/chart --wait

      - name: Install store controller
        run: helm install -n kube-system atomix-raft-controller ./stores/raft/chart --wait

      - name: Run tests
        run: ct install --charts ./drivers/raft/test
