# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "atomix-raft-controller.fullname" . }}-config
data:
{{ (.Files.Glob "crds/raft.atomix.io/*.yaml").AsConfig | indent 2 }}
  logging.yaml:  |-
    loggers:
      root:
        level: {{ .Values.logging.rootLevel }}
        output:
          stdout:
            sink: stdout
{{ toYaml .Values.logging.loggers | indent 6 }}
    sinks:
      stdout:
        encoding: {{ .Values.logging.encoding }}
        stdout: {}