# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Verify Runtime

on:
  push:
    branches:
      - 'master'
      - 'actions'
    paths:
      - 'runtime/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      component: runtime

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      component: runtime
