# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test Etcd Driver

on:
  push:
    branches:
      - 'master'
      - 'helmit'
    paths:
      - 'drivers/etcd/**'
      - 'stores/etcd/**'
      - 'testing/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        uses: ./.github/actions/docker-build
        with:
          name: controller
          context: controller
          file: controller/build/controller/Dockerfile
          tags: atomix/controller

  build-controller-init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        uses: ./.github/actions/docker-build
        with:
          name: controller-init
          context: controller
          file: controller/build/controller-init/Dockerfile
          tags: atomix/controller-init

  build-sidecar-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        uses: ./.github/actions/docker-build
        with:
          name: sidecar-controller
          context: sidecar
          file: sidecar/build/controller/Dockerfile
          tags: atomix/sidecar-controller

  build-sidecar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        uses: ./.github/actions/docker-build
        with:
          name: sidecar
          file: drivers/etcd/tests/Dockerfile
          tags: atomix/sidecar:etcd

  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    needs:
      - build-controller
      - build-controller-init
      - build-sidecar-controller
      - build-sidecar

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Helm
        uses: ./.github/actions/setup-helm

      - name: Setup Helmit
        uses: ./.github/actions/setup-helmit

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind

      - name: Fetch atomix/controller
        uses: actions/download-artifact@v3
        with:
          name: controller
          path: /tmp

      - name: Fetch atomix/controller-init
        uses: actions/download-artifact@v3
        with:
          name: controller-init
          path: /tmp

      - name: Fetch atomix/sidecar-controller
        uses: actions/download-artifact@v3
        with:
          name: sidecar-controller
          path: /tmp

      - name: Fetch atomix/sidecar
        uses: actions/download-artifact@v3
        with:
          name: sidecar
          path: /tmp

      - name: Load Docker images
        run: |
          kind load image-archive /tmp/controller.tar
          kind load image-archive /tmp/controller-init.tar
          kind load image-archive /tmp/sidecar-controller.tar
          kind load image-archive /tmp/sidecar.tar

      - name: Install core controller
        run: |
          helm install -n kube-system atomix-controller ./controller/chart --set image.pullPolicy=Never --set init.image.pullPolicy=Never --wait

      - name: Install sidecar controller
        run: |
          helm install -n kube-system atomix-sidecar-controller ./sidecar/chart --set image.pullPolicy=Never --set init.image.pullPolicy=Never --wait

      - name: Run driver tests
        working-directory: drivers/etcd/tests
        run: |
          helmit test ./... \
            --context ${{ github.workspace }} \
            --namespace test \
            --create-namespace \
            --label sidecar.atomix.io/inject=true \
            --label runtime.atomix.io/profile=etcd \
            --annotation sidecar.atomix.io/image=atomix/sidecar:etcd \
            --annotation sidecar.atomix.io/imagePullPolicy=Never \
            --verbose

      - name: Record k8s status
        if: failure()
        run: |
          echo "kubectl get pods --all-namespaces"
          kubectl get pods --all-namespaces
          echo "kubectl get storageprofiles --all-namespaces"
          kubectl get storageprofiles --all-namespaces
          echo "kubectl get datastores --all-namespaces"
          kubectl get datastores --all-namespaces
