# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

.PHONY: build
build:
	$(MAKE) -C v8 build
	$(MAKE) -C v9 build

.PHONY: test
test:
	$(MAKE) -C v8 test
	$(MAKE) -C v9 test
