# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftreplicas.raft.atomix.io
spec:
  group: raft.atomix.io
  names:
    kind: RaftReplica
    listKind: RaftReplicaList
    plural: raftreplicas
    singular: raftreplica
    shortNames:
      - rm
  conversion:
    strategy: None
  scope: Namespaced
  versions:
    - name: v1beta2
      served: true
      storage: false
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - groupID
                - replicaID
                - memberID
                - pod
                - type
                - config
              properties:
                groupID:
                  type: integer
                  minimum: 1
                replicaID:
                  type: integer
                  minimum: 1
                  maximum: 1024
                memberID:
                  type: integer
                  minimum: 1
                pod:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                type:
                  type: string
                  default: Voter
                  enum:
                    - Voter
                    - Observer
                    - Witness
                join:
                  type: boolean
                peers:
                  type: integer
            status:
              type: object
              properties:
                podRef:
                  type: object
                  required:
                    - name
                    - uid
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    namespace:
                      type: string
                    name:
                      type: string
                    uid:
                      type: string
                version:
                  type: integer
                  nullable: true
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
                role:
                  type: string
                  enum:
                    - Follower
                    - Candidate
                    - Leader
                term:
                  type: integer
                  nullable: true
                leader:
                  type: object
                  required:
                    - name
                  nullable: true
                  properties:
                    name:
                      type: string
                lastUpdated:
                  type: string
                  format: date-time
                lastSnapshotIndex:
                  type: integer
                  nullable: true
                lastSnapshotTime:
                  type: string
                  format: date-time
      additionalPrinterColumns:
        - name: Pod
          type: string
          description: The pod on which the replica is run
          jsonPath: .spec.pod.name
        - name: Group
          type: integer
          description: The Raft group identifier
          jsonPath: .spec.groupID
        - name: Type
          type: string
          description: The type of membership in the Raft group
          jsonPath: .spec.type
        - name: Role
          type: string
          description: The member's current role in the Raft cluster
          jsonPath: .status.role
        - name: Leader
          type: string
          description: The member's current leader
          jsonPath: .status.leader.name
        - name: Term
          type: integer
          description: The member's current term
          jsonPath: .status.term
        - name: Last Snapshot
          type: string
          description: The last time the member took a snapshot of its state machine
          jsonPath: .status.lastSnapshotTime
        - name: Status
          type: string
          description: The replica state
          jsonPath: .status.state
    - name: v1beta3
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - groupID
                - replicaID
                - memberID
                - pod
                - type
              properties:
                groupID:
                  type: integer
                  minimum: 1
                replicaID:
                  type: integer
                  minimum: 1
                  maximum: 1024
                memberID:
                  type: integer
                  minimum: 1
                pod:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                type:
                  type: string
                  default: Voter
                  enum:
                    - Voter
                    - Observer
                    - Witness
                join:
                  type: boolean
                peers:
                  type: integer
            status:
              type: object
              default: {}
              properties:
                podRef:
                  type: object
                  required:
                    - name
                    - uid
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    namespace:
                      type: string
                    name:
                      type: string
                    uid:
                      type: string
                version:
                  type: integer
                  nullable: true
                state:
                  type: string
                  default: Pending
                  enum:
                    - Pending
                    - Bootstrapping
                    - Joining
                    - Leaving
                    - Running
                    - Ready
                role:
                  type: string
                  enum:
                    - Follower
                    - Candidate
                    - Leader
                term:
                  type: integer
                  nullable: true
                leader:
                  type: object
                  required:
                    - name
                  nullable: true
                  properties:
                    name:
                      type: string
                lastUpdated:
                  type: string
                  format: date-time
                lastSnapshotIndex:
                  type: integer
                  nullable: true
                lastSnapshotTime:
                  type: string
                  format: date-time
      additionalPrinterColumns:
        - name: Pod
          type: string
          description: The pod on which the replica is run
          jsonPath: .spec.pod.name
        - name: Group
          type: integer
          description: The Raft group identifier
          jsonPath: .spec.groupID
        - name: Type
          type: string
          description: The type of membership in the Raft group
          jsonPath: .spec.type
        - name: Role
          type: string
          description: The member's current role in the Raft cluster
          jsonPath: .status.role
        - name: Leader
          type: string
          description: The member's current leader
          jsonPath: .status.leader.name
        - name: Term
          type: integer
          description: The member's current term
          jsonPath: .status.term
        - name: Last Snapshot
          type: string
          description: The last time the member took a snapshot of its state machine
          jsonPath: .status.lastSnapshotTime
        - name: Status
          type: string
          description: The replica state
          jsonPath: .status.state