# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftclusters.raft.atomix.io
spec:
  group: raft.atomix.io
  scope: Namespaced
  names:
    kind: RaftCluster
    listKind: RaftClusterList
    plural: raftclusters
    singular: raftcluster
    shortNames:
      - rc
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions:
        - v1
      clientConfig:
        service:
          name: atomix-raft-controller
          namespace: kube-system
          path: /convert-cluster
  versions:
    - name: v1beta2
      served: true
      storage: false
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the cluster.
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 1
                  default: 1
                image:
                  type: string
                imagePullPolicy:
                  type: string
                  enum:
                    - Never
                    - IfNotPresent
                    - Always
                imagePullSecrets:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                securityContext:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                volumeClaimTemplate:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
                averageRTT:
                  type: string
                  default: 10ms
                logging:
                  type: object
                  default: {}
                  properties:
                    encoding:
                      type: string
                      default: console
                      enum:
                        - console
                        - json
                    rootLevel:
                      type: string
                      default: info
                      enum:
                        - debug
                        - info
                        - warn
                        - error
                        - fatal
                        - panic
                    loggers:
                      type: array
                      items:
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                          level:
                            type: string
                            nullable: true
                            enum:
                              - debug
                              - info
                              - warn
                              - error
                              - fatal
                              - panic
            status:
              type: object
              default: {}
              properties:
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
                groups:
                  type: integer
      additionalPrinterColumns:
        - name: Replicas
          type: integer
          description: The number of replicas in the cluster
          jsonPath: .spec.replicas
        - name: Status
          type: string
          description: The cluster state
          jsonPath: .status.state
    - name: v1beta3
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the cluster.
              type: object
              default: {}
              properties:
                replicas:
                  type: integer
                  minimum: 1
                  default: 1
                image:
                  type: string
                imagePullPolicy:
                  type: string
                  enum:
                    - Never
                    - IfNotPresent
                    - Always
                imagePullSecrets:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                securityContext:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                averageRTT:
                  type: string
                  default: 10ms
                persistence:
                  type: object
                  default: {}
                  properties:
                    enabled:
                      type: boolean
                      default: true
                    storageClass:
                      type: string
                      nullable: true
                    accessModes:
                      type: array
                      default:
                        - ReadWriteOnce
                      items:
                        type: string
                    size:
                      type: string
                      default: 8Gi
                    selector:
                      type: object
                      properties:
                        matchLabels:
                          type: object
                          additionalProperties:
                            type: string
                        matchExpressions:
                          type: array
                          items:
                            type: object
                            required:
                              - key
                              - operator
                              - values
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                              values:
                                type: array
                                items:
                                  type: string
                logging:
                  type: object
                  default: {}
                  properties:
                    encoding:
                      type: string
                      default: console
                      enum:
                        - console
                        - json
                    rootLevel:
                      type: string
                      default: info
                      enum:
                        - debug
                        - info
                        - warn
                        - error
                        - fatal
                        - panic
                    loggers:
                      type: array
                      items:
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                          level:
                            type: string
                            nullable: true
                            enum:
                              - debug
                              - info
                              - warn
                              - error
                              - fatal
                              - panic
            status:
              type: object
              default: {}
              properties:
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
                groups:
                  type: integer
      additionalPrinterColumns:
        - name: Replicas
          type: integer
          description: The number of replicas in the cluster
          jsonPath: .spec.replicas
        - name: Status
          type: string
          description: The cluster state
          jsonPath: .status.state