# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Check License

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  check-license:
    name: Check license
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check REUSE compliance
        uses: fsfe/reuse-action@v1
        with:
          args: lint
