# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

on:
  workflow_call:
    inputs:
      component:
        type: string
        description: "The component path"
        required: true

      package:
        type: string
        description: "The package to test"
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: ./.github/actions/setup-go

      - name: Run tests
        run: go test ${{ inputs.package || format('github.com/atomix/atomix/{0}/...', inputs.component) }}
        working-directory: ${{ inputs.component }}
